HearthDeepApi/urls.py
from django.conf.urls import url
from HearthDeepApi import views
from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    url(r'^hearthlog/$', views.HearthLogList.as_view()),
    url(r'^hearthlog/(?P<pk>[0-9]+)/$', views.HearthLogDetail.as_view()),
    # url(r'^logupload/$', views.LogUploadList.as_view()),
    # url(r'^logupload/(?P<pk>[0-9]+)/$', views.LogUploadDetail.as_view()),
    url(r'^users/$', views.UserList.as_view()),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

HearthDeepWeb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from django.conf import settings
from django.conf.urls.static import static

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('clientWeb.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^user/', include(router.urls)),
    url(r'^api/', include('HearthDeepApi.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

clientWeb/urls.py
"""ClientWeb urls."""

from django.conf.urls import url
from . import views
from django.views.generic import RedirectView

app_name = "clientWeb"
urlpatterns = [
url(r'^$', views.index, name='index'),
url(r'^accounts/profile/$', RedirectView.as_view(url='/')),
url(r'^(?P<question_id>[0-9]+)/$', views.detail, name="detail"),
url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name="results"),
url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name="vote"),
]

HearthDeepApi/models.py
from __future__ import unicode_literals
# from django.contrib.auth.models import User
from django.db import models

class HearthLog(models.Model):
    brutLog = models.FileField(upload_to='logs/%Y/%m/%d/')
    created = models.DateTimeField(auto_now_add=True)
    filename = models.TextField()
    owner = models.ForeignKey('auth.User', related_name='hearthlog')

    class Meta:
        ordering = ('created',)

# class LogUpload(models.Model):
#     created = models.DateTimeField(auto_now_add=True)
#     owner = models.ForeignKey('auth.User', related_name='hearthlog')
#     datafile = models.FileField()

clientWeb/models.py
from __future__ import unicode_literals
from django.db import models
from django import forms
from django.contrib.auth.models import User
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    voites = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

HearthDeepApi/views.py
# from django.shortcuts import render
# from django.views.decorators.csrf import csrf_exempt
from rest_framework.decorators import api_view
# from django.http import HttpResponse
# from rest_framework.renderers import JSONRenderer
# from rest_framework.parsers import JSONParser
# from rest_framework import status
from rest_framework import views
from rest_framework.response import Response
from HearthDeepApi.models import HearthLog
from HearthDeepApi.serializers import HearthLogSerializer, UserSerializer
from rest_framework import generics
from rest_framework.parsers import FormParser, MultiPartParser
from rest_framework.parsers import FileUploadParser
from rest_framework.viewsets import ModelViewSet
from django.contrib.auth.models import User
from rest_framework import permissions



class HearthLogList(generics.ListCreateAPIView):
    permission_classes = (permissions.IsAuthenticated,)
    queryset = HearthLog.objects.all()
    serializer_class = HearthLogSerializer

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

class HearthLogDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (permissions.IsAuthenticated,)
    queryset = HearthLog.objects.all()
    serializer_class = HearthLogSerializer

# class LogUploadList(generics.ListCreateAPIView):
#     queryset = LogUpload.objects.all()
#     serializer_class = LogUploadSerializer
#
#     def perform_create(self, serializer):
#         serializer.save(owner=self.request.user)
#
# class LogUploadDetail(generics.RetrieveUpdateDestroyAPIView):
#     queryset = LogUpload.objects.all()
#     serializer_class = LogUploadSerializer

class UserList(generics.ListAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserDetail(generics.RetrieveAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# class LogUploadViewSet(ModelViewSet):
#     queryset = LogUpload.objects.all()
#     serializer_class = LogUploadSerializer
#     def pre_save(self, obj):
#         obj.datafile = self.request.FILES.get('file')
#
#     def perform_create(self, serializer):
#         serializer.save(owner=self.request.user, datafile=self.request.data.get('datafile'))





# class FileLogUploadView(views.APIView):
#     parser_classes = (FileUploadParser,)
#
#     def post(self, request, filename, format=None):
#         # file_obj = request.FILES['file']
#
#         # do some stuff with uploaded file
#         return Response(status=204)


# @api_view(['GET', 'POST'])
# def hearthLog_list(request, format=None):
#     if request.method == 'GET':
#         hearthLog = HearthLog.objects.all()
#         serializer = HearthLogSerializer(hearthLog, many=True)
#         return Response(serializer.data)
#
#     elif request.method == 'POST':
#         data = JSONParser().parse(request)
#         serializer = HearthLogSerializer(data=data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer, data, status=status.HTTP_201_CREATED)
#         return Response(serializer.errors, status=status.HTTP_404_NOT_FOUND)
#
# @api_view(['GET', 'PUT', 'DELETE'])
# def hearthLog_detail(request, id, format=None):
#     try:
#         hearthLog = HearthLog.objects.get(id=id)
#     except HearthLogSerializer.DoesNotExist:
#         return HttpResponse(status=status.HTTP_400_BAD_REQUEST)
#
#     if request.method == 'GET':
#         serializer = HearthLogSerializer(hearthLog)
#         return Response(serializer.data)
#
#     elif request.method == 'PUT':
#         data = JSONParser().parse(request)
#         serializer = HearthLogSerializer(hearthLog, data=data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
#
#     elif request.method == 'DELETE':
#         hearthLog.delete()
#         return HttpResponse(status=status.HTTP_204_NO_)

clientWeb/views.py
"""View ClientWeb."""
# from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from .models import Question



def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'clientWeb/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'clientWeb/detail.html', {'question': question})


def results(request, question_id):
    response = ("You are looking at the results of question %s ." % question_id)
    return HttpResponse(response)

def vote(request, question_id):
    return ("You're voting on question %s." % question_id)

clientWeb/templates/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Import icon -->
    <linklink rel="icon" type="img/ico" href="/static/client/hslogo.png" />
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="/static/client/style.css" />

    <title>{% block title %}HearthDeep{% endblock %}</title>
</head>
<div id="header">
    {% block header %}
    <nav class="blue darken-3">
        <div class="container">
            <div class="nav-wrapper z-depth-2">
                <a class="brand-logo" href="{% url 'clientWeb:index' %}">HearthDeep</a>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                {% if user.is_authenticated %}
                <ul class="right hide-on-med-and-down">
                    <li>{{ user.username }}</li>

                    <li><a href="{% url 'auth_logout' %}">{% trans "Log out" %}</a></li>
                    <li><a href="{% url 'auth_password_change' %}">{% trans "Change password" %}</a></li>
                </ul>
                <ul class="side-nav" id="mobile-demo">
                    <li>{{ user.username }}</li>

                    <li><a href="{% url 'auth_logout' %}">{% trans "Log out" %}</a></li>
                    <li><a href="{% url 'auth_password_change' %}">{% trans "Change password" %}</a></li>
                </ul>
                {% else %}
                <ul class="right hide-on-med-and-down">
                    <li><a href="{% url 'auth_login' %}">Log in</a></li>
                </ul>
                <ul class="side-nav" id="mobile-demo">
                    <li><a href="{% url 'auth_login' %}">Log in</a></li>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
    {% endblock %}
</div>

<div id="content">
    {% block content %}

    {% endblock %}
</div>
<div id="footer">
    {% block footer %}
    <hr />
    <p>
        Ananas.02
    </p>
    {% endblock %}
</div>



<!--Import jQuery before materialize.js-->
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
</body>
</html>

</html>

clientWeb/templates/base.old.html
<body>
    <div id="header">
    {% block header %}
    <a href="{% url 'clientWeb:index' %}">{% trans "Home" %}</a> |

    {% if user.is_authenticated %}
        {% trans "Logged in" %}: {{ user.username }}
        (<a href="{% url 'auth_logout' %}">{% trans "Log out" %}</a> |
        <a href="{% url 'auth_password_change' %}">{% trans "Change password" %}</a>)
    {% else %}
       <a href="{% url 'auth_login' %}">{% trans "Log in" %}</a>
    {% endif %}
    <hr />
    {% endblock %}
    </div>

    <div id="content">
    {% block content %}{% endblock %}
    </div>

    <div id="footer">
    {% block footer %}
        <hr />
        <p>
          Ananas.01
        </p>
    {% endblock %}
    </div>
</body>

clientWeb/templates/clientWeb/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

clientWeb/templates/clientWeb/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div id="index-banner">
  <div class="section">
<div class="container">
  <div class="row">
    <div class="col s12">
      <div class="card" style="background-color: rgba(255, 255,255, 0.90);">
    <div class="card-content">
      <div class="col l2 m3 s4">
        <img src="static/client/hslogo.png" class="responsive-img">
      </div>
      <div class="hide-on-med-and-up col s8">
        <h4 style="font-size:1.2rem;font-weight:400;">Hearthstone Deep Learning</h4>
      </div>
      <div class="col l10 m9 s12">
        <div class="hide-on-small-and-down">
          <h4 style="font-weight:400;">Hearthstone Deep Learning</h4>
          <div class="hide-on-large-only">
        <br>
          </div>
            <!-- <a class="waves-effect waves-light btn light-blue darken-3 right" style="margin-bottom:10px;margin-top:0px;margin-left:10px;" href="#"><i class="mdi mdi-google-play left"></i>Button 2</a><a class="waves-effect waves-light btn light-blue darken-3 text-primarycolor right" style="margin-bottom:10px;margin-top:0px;" href="#"><i class="mdi mdi-credit-card left"></i>Button 1</a> -->
          <br>
          <br><br>
        </div>
        <div class="hide-on-med-and-up center">
          <p>
        <a class="waves-effect waves-light btn light-blue darken-3" style="width: 115px;margin-bottom:10px;margin-right:10px;padding-right:0.1rem;padding-left:0.1rem;font-size: 0.8rem;" href="#">
          <i class="mdi mdi-google-play left" style="margin-right: 0px;"></i>Button 1</a>
        <a class="waves-effect waves-light btn light-blue darken-3 text-primarycolor" style="width:115px;margin-bottom:10px;margin-right:10px;padding-right: 0.1rem;padding-left:0.1rem;font-size: 0.8rem;" href="#">
          <i class="mdi mdi-credit-card left" style="margin-right: 0px;"></i>Button 2</a>
          </p>
        </div>
        <div class="divider" style="clear:both;"></div>
      </div>
      <div class="s12" style="clear:both;">
        <p class="center-align" style="color: rgba(0, 0, 0, 0.71); margin: 15px;">
            HearthDeep is a university project aimed at creating a competitive Hearthstone's artificial intelligence.
            But for this we need you! Indeed to create the ultimate player, you have to teach him to play.
            HearthDeep will recover your summary games to examine and learn new techniques by drawing on your playing style.
            So go ahead and answer the call, everyone for the best one.

        </p>
        <p class="center-align" style="color: rgba(0, 0, 0, 0.71); margin: 15px;"><a class="waves-effect waves-light btn light-blue darken-3" href="https://sourceforge.net/projects/hearthdeepclient/" style="margin-right:10px;"><i class="mdi mdi-camera left"></i>Download last version</a></p>
      </div>
    </div>
      </div>
    </div>
  </div>
</div>
  </div>
</div>

<div class="container light-blue-text text-darken-3">
  <div class="row">
<div class="col s12">
  <h5>Latest versions</h5>
  <p style="font-weight:400">
      The current version is the first one alpha. For the moment, HearthDeepClient is closed and users are selected for testing the application.
      <ul>
          <li>- Establishment of the connection system.</li>
          <li>- Hearthstone configuration for the logs generation.</li>
          <li>- Harvest historic match automatically.</li>
      </ul>
  </p>
</div>
  </div>
  <div class="row">
<div class="col s12 l6" id="versions-list">
  <ul class="collapsible mobile-list-margin" data-collapsible="accordion">
    <li>
      <div class="collapsible-header"><i class="mdi mdi-lock text-primarycolor"></i>Version Ananas 0.0.1 (latest) <a href="#!" class="secondary-content" style="font-weight:500;"></a></div>
      <div class="collapsible-body white" style="display: none;">
    <p>
        Mise en place de l'alpha.
    </p>
    <p class="docs-link"><a href="https://sourceforge.net/projects/hearthdeepclient/" target="_blank">Direct download</a></p>
      </div>
    </li>

  </ul>
</div>
  </div>
</div>
</div>

<div class="row blue darken-3">
<div class="container white-text text-white">
<h5>How it works</h5>
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eleifend quis felis non molestie. Donec nunc turpis, ultricies a ipsum in, sagittis varius mi. Mauris ante sapien, pretium eu risus non, fringilla egestas libero. Nam eu lorem consectetur, placerat lectus non, rhoncus erat. Curabitur in fermentum justo. In ac suscipit nisi. Aenean fringilla leo eget ipsum mollis, nec sollicitudin augue varius. Fusce eu finibus sapien.

  Curabitur quis blandit mi. Curabitur vel enim id lacus venenatis varius eget ut nunc. Maecenas quis neque libero. Sed sagittis ultrices lacus sagittis fermentum. Proin sit amet dui et erat posuere porttitor nec vel odio. Vivamus ut malesuada lorem. Curabitur ac bibendum nisl. Donec iaculis orci non nisl lobortis, ac accumsan turpis pellentesque. Fusce nec odio faucibus, consequat enim a, blandit orci. Vivamus lobortis, quam vitae viverra gravida, eros elit convallis lacus, eu commodo purus turpis sed mauris. Vestibulum sit amet quam laoreet, egestas enim sed, auctor lacus.

  Maecenas tincidunt eros eget lorem posuere molestie. Aliquam eu massa porttitor, dictum tortor in, rhoncus ex. Donec in sem vel nunc ornare porta vel non diam. Cras vitae tincidunt libero, nec sollicitudin eros. Maecenas rhoncus aliquet augue, sit amet convallis ipsum. Suspendisse massa augue, bibendum sed porta nec, hendrerit vitae dui. Duis a bibendum nunc, vel mollis magna. Vivamus dictum justo a purus cursus feugiat sit amet non quam. Donec orci mauris, sagittis quis fringilla ac, eleifend nec nisi. Nam purus sem, euismod in mi et, elementum consequat ligula. Integer turpis nisl, malesuada eget quam id, condimentum maximus massa. Integer posuere et dui at placerat. Pellentesque sodales ipsum mi, a finibus nunc fermentum eu. Sed posuere lectus quam, id posuere nisl cursus at. Pellentesque lobortis finibus tristique.
</p>
</div>
</div>

{% endblock %}